blueprint:
  name: Esphome-Shelly1Plus with connected button
  description: Use a button connected to a Shelly1Plus running custom EspHome to create automations for single, double and long click
  domain: automation
  source_url: https://github.com/gmlupatelli/blueprints_repo/blob/master/moes_controler/moes_double_rocker.yaml
  
  # Blueprint Inputs
  input:
    remote_switch:
      name: Select the Shelly1P to use for this automation
      description: Shelly1Plus with custom EspHome, which send single, double and long click
      selector:
        device:
          integration: esphome
          #manufacturer: _TZ3000_5e235jpa
          entity:
            domain: binary_sensor
          #   device_class: battery
    button_single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action:
    button_double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action:
    button_long_press:
      name: Long Press
      description: Action to run on long press
      default: []
      selector:
        action:
    
# Triggers
trigger:
  - platform: event
    event_type: esphome.button_pressed
    data:
      device_id: !input remote_switch
      id: "taster"

# Actions
action:
  - variables:
      # endpoint_id:  '{{ trigger.event.data.endpoint_id | int }}'
      command: '{{ trigger.event.data.command }}'

  - choose:
      - conditions:
          - '{{ command == ''remote_button_short_press'' }}'
        sequence: !input button_single_press
      - conditions:
          - '{{ command == ''remote_button_double_press''}}'
        sequence: !input button_double_press
      - conditions:
          - '{{ command == ''remote_button_long_press''}}'
        sequence: !input button_long_press

        
mode: restart
max_exceeded: silent
